version: "3.8"

services:
    cardinal:
        build: .
        container_name: cardinal
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - ~/.kube:/root/.kube:ro
        networks:
            - cardinal-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    cardinal-network:
        driver: bridge
